apiVersion: v1
kind: Namespace
metadata:
  name: metallb
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: efk-demo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/defenseunicorns/efk-demo.git
  ref:
    branch: "###ZARF_VAR_BRANCH###"
